---
title: "Module 18"
author: "Lillian Holden"
date: "2023-11-16"
output: html_document
---

### Challenge 1
```{r}
library(curl)
```

```{r}
f <- curl("https://raw.githubusercontent.com/fuzzyatelin/fuzzyatelin.github.io/master/AN588_Fall21/chimpgrooming.csv")
d <- read.csv(f, header = TRUE, sep = ",")
head(d)
```

```{r}
summary(d)
```

```{r}
# first, some exploratory visualization let's plot grooming received
# duration in relation to subject ID
par(mfrow = c(1, 1))
boxplot(data = d, duration ~ subject, col = c("lightpink1"))
```

```{r}
# we see lots of individual variation let's plot grooming received
# duration in relation to reproductive condition
boxplot(data = d, duration ~ reprocondition, col = c("burlywood2", "lightpink1"))
```

```{r}
# let's plot grooming received duration in relation to reproductive
# condition and parity
boxplot(data = d, duration ~ reprocondition * parity, col = c("burlywood2",
    "lightpink1"))
```

```{r}
boxplot(data = d, duration ~ reprocondition * subject, col = c("burlywood2",
    "lightpink1"))
```

```{r}
library(lme4)
```

```{r}
lme <- lmer(data = d, duration ~ reprocondition + parity + (1 | subject))
summary(lme)
```

```{r}
coefficients(lme)
```

```{r}
full <- lmer(data = d, duration ~ reprocondition + parity + (1 | subject), REML = FALSE)
summary(full)
```

```{r}
reduced <- lmer(data = d, duration ~ parity + (1 | subject), REML = FALSE)
summary(reduced)
```

```{r}
anova(reduced, full, test = "Chisq")
```

```{r}
full <- lmer(data = d, duration ~ reprocondition + parity + (1 | subject), REML = FALSE)
reduced <- lmer(data = d, duration ~ reprocondition + (1 | subject), REML = FALSE)
anova(reduced, full, test = "Chisq")
```

### Challenge 2
```{r}
full <- lmer(data = d, duration ~ reprocondition * parity + (1 | subject), REML = FALSE)
reduced <- lmer(data = d, duration ~ reprocondition + parity + (1 | subject),
    REML = FALSE)
anova(reduced, full, test = "Chisq")
```

```{r}
lme <- lmer(data = d, duration ~ reprocondition + parity + (1 + reprocondition |
    subject) + (1 + parity | subject), REML = FALSE)
```

```{r}
summary(lme)
```

```{r}
coefficients(lme)
```

```{r}
# reproductive condition
full <- lmer(data = d, duration ~ reprocondition + parity + (1 + reprocondition |
    subject) + (1 + parity | subject), REML = FALSE)
```

```{r}
reduced <- lmer(data = d, duration ~ parity + (1 + reprocondition | subject) +
    (1 + parity | subject), REML = FALSE)
```

```{r}
anova(reduced, full, test = "Chisq")
```

```{r}
# parity
full <- lmer(data = d, duration ~ reprocondition + parity + (1 + reprocondition |
    subject) + (1 + parity | subject), REML = FALSE)
```

```{r}
null <- lmer(data = d, duration ~ reprocondition + (1 + reprocondition | subject) +
    (1 + parity | subject), REML = FALSE)
```

```{r}
anova(reduced, full, test = "Chisq")
```

### Challenge 3
```{r}
library(AICcmodavg)
print(aictab(list(full, reduced, null), c("full", "reduced", "null")), LL = FALSE)
```

```{r}
install.packages("MuMIn")
library(MuMIn)
r.squaredGLMM(full)
```

```{r}
r.squaredGLMM(reduced)
```

```{r}
r.squaredGLMM(null)
```

Use glmer() in the packages {MCMCglmm} or {lme4} for generalized linear mixed modeling !!!

